---
title: "Forecasting Competition"
author: "Elise Boos and Justin DePue"
date: "2023-03-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(readxl)
```

## Import and Wrangle Data

```{r import and wrangle}
#read in data
load <- read_xlsx("./Competition/Data/load.xlsx")

#wrangle to summarize to daily 
load <- load %>% 
  mutate(date = ymd(date)) %>% 
  mutate(daily = rowMeans(load[,3:26])) %>%
  select(meter_id, date, daily)

#create ts 
f <- first(load$date)

#training dataset
msts <- msts(load$daily,start = c(year(f),month(f),day(f)), end = c(2010,1,1), seasonal.periods =c(7,365.25))

#full dataset 
msts_full <- msts(load$daily,start = c(year(f),month(f),day(f)), seasonal.periods =c(7,365.25))
```


#ARIMA

```{r forecast 1}
#test on till 2010
arima <- auto.arima(window(msts, end = c(2009,1)))
arima
checkresiduals(arima)
ARIMA_forecast <- forecast(object = arima, h = 365)

autoplot(msts_full) +
    autolayer(ARIMA_forecast,series="ARIMA",PI=FALSE) +
    ylab("Unit") +
    xlab("") +
    labs(col="Model")

```


```{r good models}
#run on whole data
arima <- auto.arima(msts_full,seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(msts_full, 
                                          K=c(2,2)))
arima
checkresiduals(arima)

ARIMA_forecast <- forecast(arima,
                           xreg=fourier(msts_full,
                                        K=c(2,2),
                                        h=59),
                           h=59) 
#ARIMA_forecast <- forecast(object = arima, h = 59)



autoplot(msts_full) +
    autolayer(ARIMA_forecast,series="ARIMA",PI=FALSE) +
    ylab("Unit") +
    xlab("") +
    labs(col="Model")

forecast_arima <- as.data.frame(ARIMA_forecast$mean)
write.csv(forecast_arima, "Competition/Output/forecast_arima_5.csv")
```

#STL + ETS

```{r test forecast 2}

# Test STL + ETS Model
ets_model <-  stlf(msts, h=59)

#Plot foresting results
autoplot(ets_model) + ylab("Unit")
checkresiduals(ets_model)

#Plot model + observed data
autoplot(msts_full) +
  autolayer(ets_model, series="STL + ETS",PI=FALSE) +
  ylab("Unit")

```

```{r Full forecast 2}
# Full Data STL + ETS Model

ets_model <-  stlf(msts_full, h=59)

#Plot foresting results
autoplot(ets_model) + ylab("Unit")
checkresiduals(ets_model)

#Plot model + observed data
autoplot(msts_full) +
  autolayer(ets_model, series="STL + ETS",PI=FALSE) +
  ylab("Unit")

forecast_ETS <- as.data.frame(ets_model$mean)
#write.csv(forecast_ETS, "Competition/Output/forecast_ETS.csv")
```

#TBATS

```{r tbats}
TBATS_fit <- tbats(msts_full)

TBATS_for <- forecast(msts_full, h=59)

autoplot(msts_full) +
    autolayer(TBATS_for,series="TBATS",PI=FALSE) +
    ylab("Unit") +
    xlab("") +
    labs(col="Model")

forecast_tbats <- as.data.frame(TBATS_for$mean)
#write.csv(forecast_tbats, "Competition/Output/forecast_tbats.csv")
```

# Neural Network 
```{r nn}
NN_fit <- nnetar(msts_full,p=1,P=0,xreg=fourier(msts_full, K=c(2,2)))

#NN_for <- forecast(NN_fit, h=365) 
NN_for <- forecast(NN_fit, h=59,xreg=fourier(msts_full, 
                                          K=c(2,2),h=59))

autoplot(msts_full) +
    autolayer(NN_for,series="NN",PI=FALSE) +
    ylab("Unit") +
    xlab("") +
    labs(col="Model")

forecast_NN <- as.data.frame(NN_for$mean)
#write.csv(forecast_NN, "Competition/Output/forecast_NN.csv")
```

